server:
  port: 4455

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/businessdb
    username: root
    password: root
    initialize: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


jwt:
  secret: my-secret

